### ISSUE TITLE
Very incorrect coverage displayed next to individual browser versions

### ISSUE THREAD

**Issue by jaydenseric** [browserslist/browserl.ist#170]
A lot of the coverage % displayed next to individual browser versions is very incorrect.

Example:

Firefox 69 displays 0.16% coverage:

https://browsersl.ist/?q=firefox+69

<img width="490" alt="Screen Shot 2019-12-05 at 6 39 29 pm" src="https://user-images.githubusercontent.com/1754873/70213952-a50b5680-178e-11ea-8860-3e87fb280be4.png">

You can see the correct coverage displayed at the bottom; 2.25%. This can be confirmed using the Browserslist CLI:

```
npx browserslist --coverage "firefox 69"
```

Result:

```
These browsers account for 2.55% of all users globally
```

I discovered this bug because I was extremely confused why the `> 0.5%` query was displaying Firefox 69 labeled with 0.16% coverage:

https://browsersl.ist/?q=%3E+0.5%25

<img width="978" alt="Screen Shot 2019-12-05 at 6 44 34 pm" src="https://user-images.githubusercontent.com/1754873/70214288-501c1000-178f-11ea-8045-b9e0fa4a800b.png">

**Comment by RyanThompson** [comment]
We have run into this as well and can confirm. FF 71 (~2.x%) for example disappears with the query `> 1%` currently.

Any input on this? I've yet to test on the API/real world usage to see if it's isolated to the website or not.

**Comment by mauriciabad** [comment]
It is completly off:
```
35.16% + 14% = 49.16% ≠ 58.71%
```

Maybe "Global coverage" doesn't mean the sum of the usage of the browsers  queried. In this case, an explanation would solve it.

![browserl ist_ A page to display compatible browsers from a browserslist string -000181](https://user-images.githubusercontent.com/12821361/76256730-bada5d00-6250-11ea-9604-1e956d703c6b.png)

**Comment by mauriciabad** [comment]
With `>2%`  you get results with 0.41%.

https://browserl.ist/?q=%3E2%25

![PDF Reader by Xodo-000182](https://user-images.githubusercontent.com/12821361/76257066-42c06700-6251-11ea-8fc2-d10c6ef07440.png)

**Comment by ai** [comment]
I will try to fix in during next big refactoring.

For now you can try to use CLI `npx browserslist`

**Comment by ai** [comment]
Should be fixed in next release
