### ISSUE TITLE
Converting it into an npm package/lib?

### ISSUE THREAD

**Issue by hwclass** [browserslist/browserl.ist#174]
Hi @jonrohan & folks,

I was about to ask if there is a plan to have an published version of this website as a service to update project READMEs generated from browserslist config inside package.json files? If so, I can help/would be volunteer for integrating that which would be great. wdyt? 🤔 

For example: if a project has a configuration like the following in [package.json](https://github.com/browserslist/browserslist#packagejson) file or [.browserslistrc](https://github.com/browserslist/browserslist#browserslistrc) file:

```json
"browserslist": [
    "> 1%",
    "last 2 versions",
    "ie 11"
```
The thing can be converted into something like the following as an output automatically from the what `browserl.ist` provides:
```
browsers: [{
   'ie11': {
       icon: '<PATH-FOR-THE-ICON-FILE>'
       ...
   },
   ...
}]
```
or something like this. Then this output can be put inside the readme as a markdown output like that:

| IE 11        | Chrome           | Firefox |
| ------------- |:-------------:| -----:|
| :white_check_mark:       | :white_check_mark:  | :white_check_mark:  |

Hope the desc. is enough to describe what I wanna tell in detail.

Cheers.

**Comment by ai** [comment]
I think you can do it as separated project since your UX is a little different

**Comment by sabrina981** [comment]
I am not sure what to do I don't know how I was involved in this situation. Here I am requesting a code for the security system for information about my account payment ASAP please let us know if you need anything else ASAP
