### ISSUE TITLE
Add a warning about outdated data

### ISSUE THREAD

**Issue by mgrubinger** [browserslist/browserl.ist#276]
Currently the data on the website is outdated. I understand the project is undergoing a major change including fundraising. 
I would like to suggest displaying a note at the top of the page that the information provided is currently outdated, maybe also mentioning `npx browserslist`.
If you want I can send in an PR for that.

**Comment by ai** [comment]
We have a problem with deployment, so I can't add the warning

**Comment by mgrubinger** [comment]
That sounds awful, thanks for your response through.

**Comment by Terrafire123** [comment]
Rather, perhaps there should be a line that says, "Last updated on: xx/yy/2020".

**Comment by ai** [comment]
Next versions which we will release on next week will have auto-update
