### ISSUE TITLE
Take region from GET parameter

### ISSUE THREAD

**Issue by ai** [browserslist/browserl.ist#292]
Right now, server get region from query. But in design region is changed by another select box and is not connected with queries.

I suggest adding `&region=us` GET parameter.

**Comment by a-chabin** [comment]
I have already done this `&region=us` :)
https://github.com/browserslist/browserl.ist/blob/v2/server/api/browsers.js#L16

And if there is no `&region` parameter, then we take it from the `query`.
Or do we just delete this logic and add the `<select>` to the MVP?)

**Comment by ai** [comment]
> And if there is no &region parameter, then we take it from the query.

Yes, I like the smart detection, but we need to find a way to tell the client to change the `<select>`.

**Comment by a-chabin** [comment]
> a way to tell the client to change the <select>

We always return to the client the `query` and `region` values that the server parsed. It seems we can just substitute them on the client after success fetch and render results

**Comment by a-chabin** [comment]
But there is a danger that the user will be uncomfortable that we replace his input

**Comment by ai** [comment]
Let’s take region only from `GET` to avoid thinking about complex edge cases for MVP

**Comment by a-chabin** [comment]
Fixed #297
