### ISSUE TITLE
Keep current config in `#hash`

### ISSUE THREAD

**Issue by ai** [browserslist/browserl.ist#312]
It will be useful to be able to copy current website state (at least config).

Also it will also us to make links to exact state.

**Comment by a-chabin** [comment]
- `#Hash` or `?q=`?
If `#hash`, then we should do backward compatibility with `browsers.ist'?q` ? Or has it already lost its relevance?

- Do we want to pass the `&region=` parameter to the URL?

**Comment by ai** [comment]
> If #hash, then we should do backward compatibility

Did we have `?q=` before? Yes, let’s re-use it.

> Do we want to pass the &region= parameter to the URL?

We can try. I am not sure.

**Comment by a-chabin** [comment]
> Did we have ?q= before? Yes, let’s re-use it.

Yes, we send form-data to server with value from `input[name="q"]`

https://github.com/browserslist/browserl.ist/blob/main/views/index.pug#L10
