### ISSUE TITLE
Automatic `data-query`

### ISSUE THREAD

**Issue by ai** [browserslist/browserl.ist#314]
We have links of queries to show the query:

```html
<button class="Query" data-query="defaults">defaults</button>
```

Duplicating query to the button text and `data-query` could lead to the problems. Maybe we should take a query from `button.innerText`?

Related issue: https://github.com/browserslist/browserl.ist/issues/312

**Comment by a-chabin** [comment]
I am for the option to use innerText, but you need to solve these 2 problems

![image](https://user-images.githubusercontent.com/22644149/183316471-34692fde-e524-4d11-9b08-1daa697e979c.png)

**Comment by a-chabin** [comment]
It seems that data-query can be optional (`innerText` or `data-attr`), or Pug will solve this problem :)

**Comment by ai** [comment]
We can add `innerText` processor (filter). If query starts with `not`, we will add `defaults` before.

For `browserslist: [` we do not need to do anything, since it should be a valid input, which we clean on client-side.

Users should be able to paste the whole `package.json` or only `browserslist: [` part into the field.

**Comment by ariarzer** [comment]
<img width="425" alt="Screenshot 2022-08-08 at 07 45 47" src="https://user-images.githubusercontent.com/27442574/183341349-7bc4be31-0483-464c-9103-570bfbecbcc9.png">
<img width="467" alt="Screenshot 2022-08-08 at 07 44 57" src="https://user-images.githubusercontent.com/27442574/183341366-cfa883a5-8737-42fd-93bd-0ec0964938d7.png">

There are more examples, where we need a different query, other than inner text.
I agree with Alexandr, special data-attr is better way.

**Comment by ai** [comment]
I think we should not use interactive links for `10.x.x`, `10.4.x` and `not`. They should be just `<code>`.

**Comment by ariarzer** [comment]
Then it should looks different. Because they can't look like clickable element but don't be.
And then we create a new visual unit. Do we really need it...

**Comment by ai** [comment]
> Then it should looks different. Because they can't look like clickable element but don't be.

Of course, we need another token. Otherwise, the click effect will not be clear since they are showing non standard syntax.

To avoid adding new design unit, we can put them to quotes:

> `node 10` - latest “10.x.x” version

**Comment by ariarzer** [comment]
Moreover, in the future to add some extra html-code into this type of link and innerHTML won't be suitable.

**Comment by ai** [comment]
> We may want to highlight a part of query by bold font, for example.

We can trim highlighting before using `innerHTML`

**Comment by ariarzer** [comment]
And we nay want to add any tooltip as a prompt. 

I still think that better way is keep important data away from text in interface.

**Comment by ai** [comment]
Right now, it leads to extra work and mistakes. Website should be easy to maintain. It is easy to change text and forget to update `data-query`.
