### ISSUE TITLE
Improve browsers icons

### ISSUE THREAD

**Issue by ai** [browserslist/browserl.ist#317]
Now we are doing:

```js
    iconElem.src = `/assets/browser_logos/${id}.svg`;
```

It has 2 problems:
- When Can I Use added new browser, we will have 404 error
- SVG files are not processed by Vite. For instance we do not add cache busters.

Instead we should import all icons by `import imgUrl from './img.svg'`

**Comment by ariarzer** [comment]
Is there svg-loader for vite?..

I found only [vue](https://www.npmjs.com/package/vite-svg-loader) loader.

**Comment by ai** [comment]
You don’t need SVG loader.

When you write `import svgPath from './path/to/file.svg'` you will have URL to SVG in `svgPath` variable. This is the default behavior of Vite.

```js
import imgUrl from './img.svg'

iconElem.src = imgUrl
```
